### ISSUE TITLE
Unexpected attribute BTRFS_SEND_A_FILE_OFFSET

### ISSUE THREAD

**Issue by daviessm** [sysnux/btrfs-snapshots-diff#1] opened 2016-10-20 20:18 UTC
Using kernel 4.8.3 and btrfs-progs 4.7.2 I get the following error when I do a diff:

```
$> python2 btrfs-snapshots-diff.py -p /mnt/snapshots/\@home/2016-07-28T10\:12\:53+0100 -c /mnt/snapshots/\@home/2016-10-20T03\:10\:16+0100
At subvol /mnt/snapshots/@home/2016-10-20T03:10:16+0100
Found a valid Btrfs stream header, version 1
Traceback (most recent call last):
  File "btrfs-snapshots-diff.py", line 377, in <module>
modified, commands = stream.decode()
  File "btrfs-snapshots-diff.py", line 270, in decode
'BTRFS_SEND_A_PATH', idx + self.l_head)
  File "btrfs-snapshots-diff.py", line 99, in _tlv_get_string
raise ValueError('Unexpected attribute %s' % self.send_attrs[attr])
ValueError: Unexpected attribute BTRFS_SEND_A_FILE_OFFSET
```

Is this by any chance a new attribute that's crept into the send format?

**Comment by sysnux** [comment] 2016-10-22 00:25
Hum, I can't reproduce with kernel-4.8.3 and btrfs-progs-4.8.1: my tests here just pass without error.
BTRFS_SEND_A_FILE_OFFSET already existed before 4.8 (see line 50 of btrfs-snapshots-diff.py).
Could you try to upgrade brfs-progs to version 4.8.1, and see if you still reproduce the problem?

**Comment by daviessm** [comment] 2016-10-24 16:03
Yup, same with btrfs-progs 4.8.1. Happy to help with debugging.

**Comment by sysnux** [comment] 2016-10-24 16:31
Hum, I'm not even sure how to debug that!
Does it always fail, or only for certain parent snapshots?

**Comment by daviessm** [comment] 2016-10-24 17:12
It seems to always fail, I've tried it with old and new snapshots from different subvols.

I modified the code to output the other side of the equality test in _tlv_get_string and this is the result:

```
    raise ValueError('Unexpected attribute {}: {}'.format(self.send_attrs[attr], attr_type))
ValueError: Unexpected attribute BTRFS_SEND_A_FILE_OFFSET: BTRFS_SEND_A_PATH
```

**Comment by sysnux** [comment] 2021-01-12 16:14
Could you try with latest, I took some modifications from your fork.
Closing this issue as I cannot reproduce, reopen if still present.

**Closed as completed by sysnux** 2021-01-12 16:14 UTC

**Comment by yshui** [comment] 2021-07-30 01:56
C_CLONE is decoded in the wrong order.

Kernel source:

```c

	ret = begin_cmd(sctx, BTRFS_SEND_C_CLONE);
	if (ret < 0)
		goto out;

	ret = get_cur_path(sctx, sctx->cur_ino, sctx->cur_inode_gen, p);
	if (ret < 0)
		goto out;

	TLV_PUT_U64(sctx, BTRFS_SEND_A_FILE_OFFSET, offset);
	TLV_PUT_U64(sctx, BTRFS_SEND_A_CLONE_LEN, len);
	TLV_PUT_PATH(sctx, BTRFS_SEND_A_PATH, p);
```

the decode code:

```python

                offset2, path = self._tlv_get_string('BTRFS_SEND_A_PATH', offset)
                offset2, file_offset = self._tlv_get_u64(
                    'BTRFS_SEND_A_FILE_OFFSET', offset2
                )
                offset2, clone_len = self._tlv_get_u64(
                    'BTRFS_SEND_A_CLONE_LEN', offset2
                )
                offset2, clone_uuid = self._tlv_get_uuid(
                    'BTRFS_SEND_A_CLONE_UUID', offset2
                )
                offset2, clone_transid = self._tlv_get_u64(
                    'BTRFS_SEND_A_CLONE_TRANSID', offset2
                )
                offset2, clone_path = self._tlv_get_string(
                    'BTRFS_SEND_A_CLONE_PATH', offset
                )  # BTRFS_SEND_A_CLONE8PATH
                offset2, clone_offset = self._tlv_get_u64(
                    'BTRFS_SEND_A_CLONE_OFFSET', offset2
                )
```

**Comment by chapmanjacobd** [comment] 2023-02-01 04:24
yeah I get this error on my nvme drive about 80% of the time ? For my HDDs I never got this error...

```py
At subvol /home/.snapshots/two
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
File ~/bin/btrfs-snapshots-diff-summary.py:588
    584         parser.print_help()
    587 if __name__ == "__main__":
--> 588     main()

File ~/bin/btrfs-snapshots-diff-summary.py:544, in main()
    542 if stream.version is None:
    543     exit(1)
--> 544 commands, paths = stream.decode(bogus=args.bogus)
    546 if args.stats:
    547     from collections import Counter

File ~/bin/btrfs-snapshots-diff-summary.py:285, in BtrfsStream.decode(self, bogus)
    275     commands.append(
    276         {
    277             "command": cmd_short,
   (...)
    281         }
    282     )
    284 elif command == "BTRFS_SEND_C_CLONE":
--> 285     offset2, path = self._tlv_get_string("BTRFS_SEND_A_PATH", offset)
    286     offset2, file_offset = self._tlv_get_u64("BTRFS_SEND_A_FILE_OFFSET", offset2)
    287     offset2, clone_len = self._tlv_get_u64("BTRFS_SEND_A_CLONE_LEN", offset2)

File ~/bin/btrfs-snapshots-diff-summary.py:103, in BtrfsStream._tlv_get_string(self, attr_type, index)
    101 attr, l_attr = unpack("<HH", self.stream[index : index + self.l_tlv])
    102 if self.send_attrs[attr] != attr_type:
--> 103     raise ValueError(f"Unexpected attribute {self.send_attrs[attr]}")
    104 (ret,) = unpack(f"<{l_attr}s", self.stream[index + self.l_tlv : index + self.l_tlv + l_attr])
    105 return index + self.l_tlv + l_attr, ret.decode("utf8")

ValueError: Unexpected attribute BTRFS_SEND_A_FILE_OFFSET
> /home/xk/bin/btrfs-snapshots-diff-summary.py(103)_tlv_get_string()
    101         attr, l_attr = unpack("<HH", self.stream[index : index + self.l_tlv])
    102         if self.send_attrs[attr] != attr_type:
--> 103             raise ValueError(f"Unexpected attribute {self.send_attrs[attr]}")
    104         (ret,) = unpack(f"<{l_attr}s", self.stream[index + self.l_tlv : index + self.l_tlv + l_attr])
    105         return index + self.l_tlv + l_attr, ret.decode("utf8")

ipdb> a
self = <__main__.BtrfsStream object at 0x7ffad57efb10>
attr_type = 'BTRFS_SEND_A_PATH'
index = 15282621
ipdb> u
> /home/xk/bin/btrfs-snapshots-diff-summary.py(285)decode()
    283 
    284             elif command == "BTRFS_SEND_C_CLONE":
--> 285                 offset2, path = self._tlv_get_string("BTRFS_SEND_A_PATH", offset)
    286                 offset2, file_offset = self._tlv_get_u64("BTRFS_SEND_A_FILE_OFFSET", offset2)
    287                 offset2, clone_len = self._tlv_get_u64("BTRFS_SEND_A_CLONE_LEN", offset2)

ipdb> a
self = <__main__.BtrfsStream object at 0x7ffad57efb10>
bogus = False
ipdb> u
> /home/xk/bin/btrfs-snapshots-diff-summary.py(544)main()
    542     if stream.version is None:
    543         exit(1)
--> 544     commands, paths = stream.decode(bogus=args.bogus)
    545 
    546     if args.stats:

ipdb> a
ipdb> u
*** Oldest frame
```

hmmm btsdu has a problem with the snapshot diff also

```sh
sudo ~/.cargo/bin/btsdu -s /tmp/btrfs_diffbI4qc
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: InvalidData, error: "item 1 does not exist"

sudo ~/.cargo/bin/btsdu -p /home/.snapshots/one /home/.snapshots/two
At subvol /home/.snapshots/two
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: InvalidData, error: "item 1 does not exist" }', /home/xk/.cargo/registry/src/github.com-1ecc6299db9ec823/btsdu-0.1.0/src/main.rs:167:45
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

# the other way around also
sudo ~/.cargo/bin/btsdu -p /home/.snapshots/two /home/.snapshots/one
At subvol /home/.snapshots/one
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: InvalidData, error: "item 1 does not exist" }'
```

```
sudo dnf info btrfs-progs 
Last metadata expiration check: 0:00:24 ago on Tue Jan 31 22:24:40 2023.
Installed Packages
Name         : btrfs-progs
Version      : 6.1.3
Release      : 1.fc37
Architecture : x86_64

uname -a
Linux pakon 6.1.8-200.fc37.x86_64
```

**Comment by raxod502** [comment] 2024-01-31 04:27
Confirming this is still an issue with the latest version of this repo. Maybe it can be re-opened?

```
% sudo ./btrfs-snapshots-diff.py -p /mnt/raw/@.restored -c /mnt/raw/@.broken
Traceback (most recent call last):
  File "/home/raxod502/files/code/utils/btrfs-snapshots-diff/./btrfs-snapshots-diff.py", line 653, in <module>
    main()
  File "/home/raxod502/files/code/utils/btrfs-snapshots-diff/./btrfs-snapshots-diff.py", line 620, in main
    commands, paths = stream.decode(bogus=args.bogus)
  File "/home/raxod502/files/code/utils/btrfs-snapshots-diff/./btrfs-snapshots-diff.py", line 325, in decode
    offset2, path = self._tlv_get_string('BTRFS_SEND_A_PATH', offset)
  File "/home/raxod502/files/code/utils/btrfs-snapshots-diff/./btrfs-snapshots-diff.py", line 105, in _tlv_get_string
    raise ValueError(f'Unexpected attribute {self.send_attrs[attr]}')
ValueError: Unexpected attribute BTRFS_SEND_A_FILE_OFFSET
```
